version: "3.8"
services:
  pagepals:
    container_name: pagepals
    
    build:
      context: .
      target: prod
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DATABASE_URL=postgres://pagepals:UNB1Gt7W3GEi3NFhBfTsGVF9wi32OGTz@dpg-cp55o0779t8c73epesg0-a.oregon-postgres.render.com/pagepals
    env_file:
      - .env
    ports:
      - 8080:8080
  
  pagepals-db:
    container_name: pagepals-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pagepals
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes: 
  postgres-data: {}
