version: "3.8"
services:
  pagepals:
    container_name: pagepals
    build:
      context: .
      target: prod
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  postgres:
    container_name: pagepals-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pagepals-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
